import type { Metadata } from 'next';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const vazirfont = localFont({
  src: '../../public/font/Vazirmatn-Regular.woff2',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-slate-200 ${vazirfont.className}`}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
