import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "./layout/header";
import Sidebar from "./layout/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirfont = localFont({
  src: '../public/font/Vazirmatn-Regular.woff2'
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#060B26] text-slate-200 ${vazirfont.className}`}>
      <Header/>
        <main className="p-5 justify-between md:flex md:flex-row xl:px-20 ">
          {children}
          <Sidebar/>
        </main>
      </body>
    </html>
  );
}
