import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { GoHome } from 'react-icons/go';
import { PiUsersThreeDuotone } from 'react-icons/pi';

// import { TbUserEdit } from 'react-icons/tb';
import Sidebar from '@/app/components/layout/sidebar';

// import Header from '../../components/layout/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sansfont = localFont({
  src: '../../../public/font/IRANSansWeb.woff',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const routes = [
    {
      text: 'نماینده ها',
      icon: <GoHome size={26} />,
      path: '/admin/panel/resellers',
    },
    // {
    //   text: 'ساخت کاربر',
    //   icon: <TbUserEdit size={26} />,
    //   path: '/dashboard/create',
    // },
    {
      text: 'تنظیمات',
      icon: <PiUsersThreeDuotone size={26} />,
      path: '/admin/panel/setting',
    },
  ];

  return (
    <body className="h-max bg-tprimary-400 md:h-[100vh]">
      <main
        className={`justify-between dark md:flex md:flex-row ${sansfont.className}`}
      >
        <Sidebar routes={routes} />
        <section className="grow">
          {/* <Header /> */}
          {children}
        </section>
      </main>
    </body>
  );
}
