import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { GoHome } from 'react-icons/go';
import { PiUsersThreeDuotone } from 'react-icons/pi';

import AdminNav from '@/app/components/layout/AdminNav';
import Sidebar from '@/app/components/layout/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sansfont = localFont({
  src: '../../../public/font/IRANSansWeb.woff',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const routes = [
    {
      text: 'نماینده ها',
      icon: <GoHome size={26} />,
      path: '/admin/panel/resellers',
    },
    {
      text: 'تنظیمات',
      icon: <PiUsersThreeDuotone size={26} />,
      path: '/admin/panel/setting',
    },
  ];

  return (
    <body className="min-h-screen bg-tprimary-400">
      <main
        className={`justify-between dark md:flex md:flex-row ${sansfont.className}`}
      >
        <Sidebar routes={routes} />
        <section className="min-h-screen grow">
          <AdminNav />
          {children}
        </section>
      </main>
    </body>
  );
}
